### ISSUE TITLE
Specialized Case Assistance for Falcon Software

### ISSUE THREAD

**Issue by tjm0043** [arif-zaman/throughput-optimization#7]
Hello, I am a researcher working for The University of Alabama in Huntsville Computer Science Department. I am attempting to use Falcon as part of a file transfer study. 

The issue currently is that we don't have access to the server we are pulling from, so we cannot use the sender half of the code. The server we are pulling from is an AWS S3 bucket. 

Would it be possible to modify or customize the code to pull from an S3 bucket without the sender code being installed by the server? Additionally, are there any offshoots or updated versions of Falcon that are more suited for this use case, and is there further documentation of Falcon that could assist us in modifications to the code for our use case?

**Comment by arif-zaman** [comment]
Hello! 
You should be able to modify Falcon for this purpose. For example, suppose you have a list of files to download. In that case, you can get them concurrently and use the optimizer (search functions) to find the most suitable concurrency value for available network bandwidth and I/O performance. In that case, one possible utility function for optimization algorithms might be throughput/concurrency. 

I apologize for the lack of proper documentation; we will address this soon. In addition, we plan to release a more general-purpose data transfer tool for easier installation and broader use cases. But, unfortunately, we don't have anything to help you right now.
